import{a as b,S as v,i as c}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function L(r,t,s){return(await b.get("https://pixabay.com/api/",{params:{key:"50311128-48dd02331c2e5a3f7eb5afcac",q:r,page:t,per_page:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const d=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function S(r){const t=r.map(s=>{const{webformatURL:a,largeImageURL:e,tags:o,likes:i,views:g,comments:h,downloads:w}=s;return`
      <li class="gallery-item">
        <a href="${e}"><img class="gallery-image" src="${a}" alt="${o}"/></a>
        <div class="stats">
          <p><span>Likes</span><span>${i}</span></p>
          <p><span>Views</span><span>${g}</span></p>
          <p><span>Comments</span><span>${h}</span></p>
          <p><span>Downloads</span><span>${w}</span></p>
        </div>
      </li>
        `}).join("");d.insertAdjacentHTML("beforeend",t),q.refresh()}function C(){d.innerHTML=""}function B(){p.style.visibility="visible"}function M(){p.style.visibility="hidden"}function $(){m.style.visibility="visible"}function f(){m.style.visibility="hidden"}const O=document.querySelector(".form"),P=document.querySelector(".load-more");let n,l=1;const u=15;O.addEventListener("submit",r=>{r.preventDefault(),f(),C(),n=r.target.elements["search-text"].value.trim(),n&&(l=1,y(n))});P.addEventListener("click",()=>{f(),l++,y(n)});async function y(r){B();try{const t=await L(r,l,u),s=t.hits;s&&s.length>0?(S(s),x(),l>=Math.ceil(t.totalHits/u)?c.show({title:"ℹ️",message:"We're sorry, but you've reached the end of search results.",messageColor:"white",titleColor:"white",backgroundColor:"#4CAF50",position:"topRight"}):$()):c.show({title:"❌",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",titleColor:"white",backgroundColor:"#ef4040",position:"topRight"})}catch(t){console.error(t)}finally{M()}}function x(){const r=document.querySelector(".gallery .gallery-item");if(!r)return;const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
